name: Deployment pipeline healthcheck

jobs:
  healthcheck:
    runs-on: ubuntu-18.04
    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v1.4
      url: https://paco-pokedex-app.herokuapp.com/
      follow-redirect: no
      max-attempts: 3 
      retry-delay: 5s