on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-18.04
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          job_name: Slack Notification
          icon_url: https://avatars.githubusercontent.com/u/64326252?s=60&v=4
          github_base_url: https://github.com/PacoZG # Specify your GHE
          status: ${{ job.status }}
          fields: repo,message,commit,author,took
          mention: here
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        if: ${{ always() }}