on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: general
        SLACK_COLOR: '#3278BD'
        SLACK_ICON: https://avatars.githubusercontent.com/u/64326252?s=60&v=4
        SLACK_MESSAGE: 'Pull request to deploy the :rocket:'
        SLACK_TITLE: Notification
        SLACK_USERNAME: PacoZG
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}